Repository Mallicyberdev/CITS5505-GroupProject-2025, pull requests merged in 2025-05, with the labels that each got.

#73 Add user listing and shared users retrieval endpoints; refactor sharing modal script
  app/auth/routes.py
  app/data_handling/routes.py
  app/templates/base.html
  app/templates/dashboard/details.html
  app/templates/home.html
Labels: bug

#77 Implement CSRF protection in the application
  app/__init__.py
  app/templates/dashboard/details.html
Labels: enhancement

#76 Update route when logged in/signed in it routes to dashboard, and whe…
  app/auth/routes.py
  app/templates/base.html
Labels: bug

#79 55-optimize-emotion-recognition
  app/main/routes.py
  app/static/css/diary.css
  app/templates/dashboard/details.html
  app/templates/dashboard/home.html
  app/templates/dashboard/shared.html
Labels: new function
